user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

home:
  path: /spin
  defaults: { _controller: PlatformBundle:Home:index }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

houses:
  path: /houses
  defaults: { _controller: AppBundle:House:index }

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

challenges:
  path: /challenges
  defaults: { _controller: AppBundle:Defis:index }

add_challenge:
  path: /add_challenge
  defaults: { _controller: AppBundle:Defis:new }

team_list:
  path: /houses/{teamName}
  defaults: { _controller: AppBundle:House:listTeam }

nameList:
  path: /nameList
  defaults: { _controller: PlatformBundle:Home:getName }


answers_list:
  path: /view_answers
  defaults: { _controller: AppBundle:Answer:viewAnswers }


